version: "3"

vars:
    GOOS: "{{default OS .GOOS}}"
    MVNW: '{{if eq .GOOS "windows"}}cmd /c mvnw.cmd{{else}}./mvnw{{end}}'
    DC_DIR: "deployment/docker-compose"
    INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"
    APPS_DC_FILE: "{{.DC_DIR}}/apps.yml"
    MONITORING_DC_FILE: "{{.DC_DIR}}/monitoring.yml"
    SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'

tasks:
    default:
        cmds:
            - task: test
    test:
        cmds:
            - "{{.MVNW}} clean verify"

    build:
        cmds:
            - "{{.MVNW}} -pl books-service spring-boot:build-image -DskipTests"
            - docker build -t ansbeno/story-corner-frontend ./frontend

    start_infra:
        cmds:
            - "docker compose -f {{.INFRA_DC_FILE}} up -d"

    stop_infra:
        cmds:
            - "docker compose -f {{.INFRA_DC_FILE}} stop"
            - "docker compose -f {{.INFRA_DC_FILE}} rm -f"

    restart_infra:
        cmds:
            - task: stop_infra
            - task: sleep
            - task: start_infra

    start:
        deps: [build]
        cmds:
            - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} up -d"

    stop:
        cmds:
            - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} stop"
            - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} rm -f"

    restart:
        cmds:
            - task: stop
            - task: sleep
            - task: start

    sleep:
        vars:
            DURATION: "{{default 5 .DURATION}}"
        cmds:
            - "{{.SLEEP_CMD}} {{.DURATION}}"
