name: "story-corner-app"
services:
    books-service:
        image: ansbeno/story-corner-service
        container_name: books-service
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - DB_URL=jdbc:postgresql://books-db:5432/postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        ports:
            - "8081:8081"
        restart: unless-stopped
        depends_on:
            books-db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    memory: 700m

    frontend:
        image: ansbeno/story-corner-frontend
        container_name: frontend
        ports:
            - "4200:80"
        restart: unless-stopped
